### PR TITLE
Part6

### PR DESCRIPTION
**Pull request by Naumych**

### CODE REVIEW

**Comment by svidlonix** [comment]
@Naumych I know it's not so easy but I believe you do your best. Please try follow principle DRY and try to optimise your code more if this comment unclear let me know.

**Comment by svidlonix** [comment]
@Naumych something wrong with validation, please test your features:
 http://pix.toile-libre.org/upload/original/1563976857.png
And one more strange behavior please check it:
http://pix.toile-libre.org/upload/original/1563977394.png

**Comment by svidlonix** [comment]
@Naumych and one more thing please write description to PR.

**Comment by Naumych** [comment]
> @Naumych I know it's not so easy but I believe you do your best. Please try follow principle DRY and try to optimize your code more if this comment unclear let me know
Moved valid? validate! in Instances

**Comment by Naumych** [comment]
> @Naumych something wrong with validation, please test your features:
> http://pix.toile-libre.org/upload/original/1563976857.png
> And one more strange behavior please check it:
> http://pix.toile-libre.org/upload/original/1563977394.png

Fixed

**Pull request merged**
